import type { Locale } from '../data/translations';
import { studioCopy, getStudioFaq } from '../data/studio-copy';
import { refreshCopy } from '../data/refresh-copy';

const text = {
 uk: {
  nav:['Продукт','Рішення','Можливості','Вигода','Безпека','Тарифи'],pilot:'Спробувати пілот',calculate:'Розрахувати вигоду',
  title:'Оплата, що відчувається',accent:'природно.',intro:'Pay by Bank для щоденної роботи. QR, NFC та посилання — без окремого POS-термінала.',badges:['0 ₴ за термінал','На ваш IBAN','ПРРО за налаштуванням'],
  stats:[['0 ₴','за окремий POS-термінал'],['3','способи: QR · NFC · Link'],['до 10 с','миттєвий переказ СЕП*']],statsNote:'*Для банків і операцій, що підтримують миттєвий переказ СЕП. Не гарантія часу checkout або підтвердження Rahunok.',source:'Джерело: НБУ',
  demoTitle:'Один рахунок. Три прості кроки.',demoSteps:['Каса','Банк клієнта','Сервер'],create:'Створити рахунок',confirm:'Підтвердити демо-оплату',verify:'Показати відповідь сервера',reset:'Новий рахунок',pending:'Очікує підтвердження',success:'Оплачено · демо',idle:'Готовий до роботи',amount:'Сума рахунку, ₴',invalid:'Вкажіть суму від 1 до 1 000 000 ₴.',demoDisclaimer:'Локальна симуляція. Без реальних переказів і запитів до банків.',openDemo:'Спробувати живе демо',
  casesTitle:'Різний бізнес. Природний сценарій.',caseTabs:['HoReCa','Retail','Послуги','Online / API'],mockLabels:['Столик 04 · Тераса','Каса 02 · Магазин','Запис · Консультація','POST /invoices'],mockItems:[['Кава × 2','Сніданок × 1'],['Кошик · 3 товари','До сплати'],['Консультація · 60 хв','Посилання для клієнта'],['order_id: 1042','status: pending']],
  featureTitle:'Екосистема можливостей.',comparisonTitle:'Не ще один термінал. Інший підхід.',comparisonHeads:['Що порівнюємо','POS-еквайринг','Rahunok / Pay by Bank'],comparisonRows:[['Обладнання','Термінал або сумісний SoftPOS','Браузер, QR або посилання'],['Дія клієнта','Картка чи цифровий гаманець','Підтвердження у своєму банку'],['Зарахування','За умовами еквайра','На IBAN, за умовами банку'],['Вартість','Комісія, можлива оренда','Тариф сервісу та можливі збори банку'],['Підтвердження','Статус від еквайра','Звірений статус рахунку'],['Фіскалізація','Окреме налаштування ПРРО','Підключений і налаштований ПРРО']],
  roiTitle:'Порахуйте різницю. На ваших умовах.',roiNote:'Порівняйте повну вартість, а не лише відсоток.',invalidCost:'Перевірте всі поля: суми ≥ 0, ставки 0–100%, кількість терміналів — ціле число 0–50.',
  planTitle:'Коли термінал підводить, робота триває.',planSteps:['Відкрийте касу в браузері','Покажіть QR або надішліть Link','Перевірте оплату перед видачею'],planNote:'Потрібні інтернет, доступний банк і попереднє налаштування. Це резервний канал, а не офлайн-оплата.',
  securityTitle:'Гроші — між банками. Контроль — у вас.',securityIntro:'У прямому A2A-сценарії платник підтверджує переказ у своєму банку на IBAN бізнесу. Rahunok організовує рахунок і його статус, а не проміжний баланс для коштів.',bank:'Банк клієнта',business:'IBAN бізнесу',funds:'Рух коштів',statusPath:'Рахунок → звірка → статус',securityCards:[['Zero-custody','Без проміжного гаманця Rahunok у прямому A2A-сценарії.'],['Статус, не скриншот','Замовлення видається після перевірки надходження.'],['Чек — окремий крок','Фіскальний документ створює налаштований ПРРО.']],
  pricingTitle:'Почніть з малого. Зростайте у своєму темпі.',finalTitle:'Почнемо з вашого бізнесу.',finalText:'Розкажіть, як працює ваша каса. Разом визначимо сценарій пілота, доступні банки й умови — до першої реальної оплати.',contact:'Поговорити з командою',company:'Компанія',contacts:'Контакти',legal:'Інформація',rights:'Усі права захищено.',footerText:'Платіжна інфраструктура для бізнесу в Україні.',motion:'Анімація фону',mock:'Демонстраційний інтерфейс',receipt:'Рахунок №1042',revenue:'Обсяг оплат сьогодні',orders:'Оплачені рахунки',customer:'Клієнт',terminal:'Каса',caption:'Живий продукт. Знайомий інтерфейс.'
 },
 en: {
  nav:['Product','Solutions','Features','Savings','Security','Pricing'],pilot:'Try a pilot',calculate:'Calculate savings',title:'Payments that feel',accent:'natural.',intro:'Pay by Bank for everyday business. QR, NFC and links — without a separate POS terminal.',badges:['No separate terminal cost','To your IBAN','Configured fiscal service'],
  stats:[['0 UAH','for a separate POS terminal'],['3','ways: QR · NFC · Link'],['≤10 s','instant SEP transfer*']],statsNote:'*For banks and transactions supporting instant SEP transfers. Not a Rahunok checkout or confirmation SLA.',source:'Source: NBU',
  demoTitle:'One invoice. Three simple steps.',demoSteps:['Checkout','Customer bank','Server'],create:'Create invoice',confirm:'Confirm demo payment',verify:'Show server response',reset:'New invoice',pending:'Awaiting confirmation',success:'Paid · demo',idle:'Ready',amount:'Invoice amount, UAH',invalid:'Enter an amount from 1 to 1,000,000 UAH.',demoDisclaimer:'Local simulation. No real transfers or bank requests.',openDemo:'Try the live demo',
  casesTitle:'Different businesses. A natural fit.',caseTabs:['HoReCa','Retail','Services','Online / API'],mockLabels:['Table 04 · Terrace','Checkout 02 · Store','Booking · Consultation','POST /invoices'],mockItems:[['Coffee × 2','Breakfast × 1'],['Basket · 3 items','Amount due'],['Consultation · 60 min','Customer payment link'],['order_id: 1042','status: pending']],
  featureTitle:'An ecosystem of possibilities.',comparisonTitle:'Not another terminal. Another approach.',comparisonHeads:['Compare','POS acquiring','Rahunok / Pay by Bank'],comparisonRows:[['Equipment','Terminal or compatible SoftPOS','Browser, QR or link'],['Customer action','Card or digital wallet','Confirmation in their bank'],['Settlement','Acquirer terms apply','To IBAN, bank terms apply'],['Cost','Fees and possible terminal rent','Service tariff and possible bank fees'],['Confirmation','Acquirer status','Reconciled invoice status'],['Fiscalisation','Separate fiscal configuration','Connected, configured fiscal service']],
  roiTitle:'Calculate the difference. On your terms.',roiNote:'Compare the total cost, not just a percentage.',invalidCost:'Check all fields: amounts ≥ 0, rates 0–100%, terminal count must be an integer 0–50.',
  planTitle:'When the terminal stops, keep going.',planSteps:['Open checkout in a browser','Show QR or send a link','Check payment before fulfilment'],planNote:'Requires internet, an available bank and prior setup. A backup channel, not offline payments.',
  securityTitle:'Money between banks. Control with you.',securityIntro:'In the direct A2A flow, customers confirm a transfer in their bank to your business IBAN. Rahunok organises the invoice and its status, not an intermediate funds balance.',bank:'Customer bank',business:'Business IBAN',funds:'Funds flow',statusPath:'Invoice → reconciliation → status',securityCards:[['Zero-custody','No intermediate Rahunok wallet in the direct A2A flow.'],['Status, not a screenshot','Fulfil orders after checking receipt of funds.'],['A separate fiscal step','A configured fiscal service creates the fiscal document.']],
  pricingTitle:'Start small. Grow at your pace.',finalTitle:'Let’s start with your business.',finalText:'Tell us how your checkout works. Together, define a pilot, available banks and terms before the first real payment.',contact:'Talk to the team',company:'Company',contacts:'Contacts',legal:'Information',rights:'All rights reserved.',footerText:'Payment infrastructure for businesses in Ukraine.',motion:'Background animation',mock:'Illustrative interface',receipt:'Invoice #1042',revenue:'Payment volume today',orders:'Paid invoices',customer:'Customer',terminal:'Checkout',caption:'A living product. A familiar interface.'
 },
 pl: {
  nav:['Produkt','Rozwiązania','Możliwości','Oszczędności','Bezpieczeństwo','Cennik'],pilot:'Wypróbuj pilotaż',calculate:'Oblicz korzyść',title:'Płatności, które są',accent:'naturalne.',intro:'Pay by Bank w codziennej pracy. QR, NFC i linki — bez osobnego terminala POS.',badges:['Bez osobnego terminala','Na Twój IBAN','Skonfigurowana fiskalizacja'],
  stats:[['0 UAH','za osobny terminal POS'],['3','sposoby: QR · NFC · Link'],['≤10 s','natychmiastowy przelew SEP*']],statsNote:'*Dla banków i operacji obsługujących natychmiastowe przelewy SEP. Nie jest to SLA checkout ani potwierdzenia Rahunok.',source:'Źródło: NBU',
  demoTitle:'Jeden rachunek. Trzy proste kroki.',demoSteps:['Kasa','Bank klienta','Serwer'],create:'Utwórz rachunek',confirm:'Potwierdź płatność demo',verify:'Pokaż odpowiedź serwera',reset:'Nowy rachunek',pending:'Oczekuje na potwierdzenie',success:'Opłacono · demo',idle:'Gotowe',amount:'Kwota rachunku, UAH',invalid:'Wpisz kwotę od 1 do 1 000 000 UAH.',demoDisclaimer:'Lokalna symulacja. Bez prawdziwych przelewów i zapytań do banków.',openDemo:'Wypróbuj demo',
  casesTitle:'Różne firmy. Naturalny scenariusz.',caseTabs:['HoReCa','Retail','Usługi','Online / API'],mockLabels:['Stolik 04 · Taras','Kasa 02 · Sklep','Rezerwacja · Konsultacja','POST /invoices'],mockItems:[['Kawa × 2','Śniadanie × 1'],['Koszyk · 3 produkty','Do zapłaty'],['Konsultacja · 60 min','Link dla klienta'],['order_id: 1042','status: pending']],
  featureTitle:'Ekosystem możliwości.',comparisonTitle:'Nie kolejny terminal. Inne podejście.',comparisonHeads:['Porównanie','POS acquiring','Rahunok / Pay by Bank'],comparisonRows:[['Sprzęt','Terminal lub zgodny SoftPOS','Przeglądarka, QR lub link'],['Działanie klienta','Karta lub portfel cyfrowy','Potwierdzenie w swoim banku'],['Księgowanie','Warunki agenta rozliczeniowego','Na IBAN, według warunków banku'],['Koszt','Prowizja i możliwy wynajem','Taryfa serwisu i możliwe opłaty banku'],['Potwierdzenie','Status agenta rozliczeniowego','Uzgodniony status rachunku'],['Fiskalizacja','Osobna konfiguracja','Podłączona usługa fiskalna']],
  roiTitle:'Oblicz różnicę. Na swoich warunkach.',roiNote:'Porównaj pełny koszt, nie tylko procent.',invalidCost:'Sprawdź pola: kwoty ≥ 0, stawki 0–100%, liczba terminali musi być całkowita 0–50.',
  planTitle:'Gdy terminal zawodzi, pracuj dalej.',planSteps:['Otwórz kasę w przeglądarce','Pokaż QR lub wyślij link','Sprawdź wpłatę przed wydaniem'],planNote:'Wymaga internetu, dostępnego banku i wcześniejszej konfiguracji. Kanał zapasowy, nie płatność offline.',
  securityTitle:'Środki między bankami. Kontrola u Ciebie.',securityIntro:'W bezpośrednim scenariuszu A2A klient potwierdza przelew w swoim banku na IBAN firmy. Rahunok organizuje rachunek i status, a nie pośrednie saldo środków.',bank:'Bank klienta',business:'IBAN firmy',funds:'Przepływ środków',statusPath:'Rachunek → uzgodnienie → status',securityCards:[['Zero-custody','Bez pośredniego portfela Rahunok w scenariuszu A2A.'],['Status, nie zrzut ekranu','Wydaj zamówienie po sprawdzeniu wpływu środków.'],['Osobny krok fiskalny','Dokument tworzy skonfigurowana usługa fiskalna.']],
  pricingTitle:'Zacznij od małego. Rozwijaj się we własnym tempie.',finalTitle:'Zacznijmy od Twojej firmy.',finalText:'Opowiedz, jak działa Twoja kasa. Wspólnie określimy pilotaż, dostępne banki i warunki przed pierwszą płatnością.',contact:'Porozmawiaj z zespołem',company:'Firma',contacts:'Kontakt',legal:'Informacje',rights:'Wszelkie prawa zastrzeżone.',footerText:'Infrastruktura płatnicza dla firm w Ukrainie.',motion:'Animacja tła',mock:'Interfejs demonstracyjny',receipt:'Rachunek #1042',revenue:'Dzisiejszy wolumen płatności',orders:'Opłacone rachunki',customer:'Klient',terminal:'Kasa',caption:'Żywy produkt. Znajomy interfejs.'
 }
};
export function getBaselineCopy(locale: Locale) {
 return {...text[locale], shared:refreshCopy[locale], product:studioCopy[locale], faq:getStudioFaq(locale)};
}
export type BaselineCopy = ReturnType<typeof getBaselineCopy>;
export const pilotHref='mailto:rahunok@rahunok.com?subject=Rahunok%20pilot';