<script lang="ts">
 import { QrCode, Check, ArrowUpRight, Coffee, ShoppingBag, Calendar, Code, LayoutDashboard, Receipt, Store } from '@lucide/svelte';
 import type { BaselineCopy } from './copy';
 import type { Locale } from '../data/translations';
 let {c,locale,variant=0,compact=false,paid=false,amount=490}:{c:BaselineCopy;locale:Locale;variant?:number;compact?:boolean;paid?:boolean;amount?:number}=$props();
 const icons=[Coffee,ShoppingBag,Calendar,Code];const Icon=$derived(icons[variant]);
 const money=(n:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(n);
</script>
<div class="b-product" class:b-compact={compact} role="group" aria-label={`${c.mock}: ${c.caseTabs[variant]}`}>
 {#if !compact}<div class="b-dashboard"><div class="b-product-chrome"><span>● ● ●</span><span>business.rahunok</span><span>↗</span></div><div class="b-dashboard-body"><aside><strong>R.</strong><LayoutDashboard size={18}/><Store size={18}/><Receipt size={18}/></aside><div class="b-dashboard-content"><div class="b-product-top"><b>{c.product.overview}</b><span class="b-demo-label">DEMO</span></div><div class="b-mock-metrics"><div><small>{c.revenue}</small><strong>{money(24850+(paid?amount:0))} ₴</strong></div><div><small>{c.orders}</small><strong>{48+(paid?1:0)}</strong></div></div><div class="b-mock-chart" aria-hidden="true">{#each [24,38,30,57,42,70,55,85,67,94,76,100] as height,i (i)}<i style:height={`${height}%`}></i>{/each}</div><div class="b-mock-row"><span>{c.mockLabels[0]}</span><b>{money(amount)} ₴</b><span class="b-status" class:b-paid={paid}>{paid?c.success:c.pending}</span></div><div class="b-mock-row"><span>{c.mockLabels[1]}</span><b>850 ₴</b><Check size={16}/></div></div></div></div>{/if}
 <div class="b-phone"><div class="b-phone-island" aria-hidden="true"></div><div class="b-phone-heading"><span>9:41</span><strong>Rahunok</strong><span>5G</span></div><div class="b-phone-merchant"><span><Icon size={23}/></span><b>{c.mockLabels[variant]}</b><small>{c.receipt}</small></div><strong class="b-phone-amount">{money(amount)}<small> ₴</small></strong><div class="b-phone-items">{#each c.mockItems[variant] as item (item)}<div><span>{item}</span><span>✓</span></div>{/each}</div>{#if variant===3}<pre class="b-api-preview">{JSON.stringify({amount,currency:'UAH',status:paid?'paid':'pending'},null,2)}</pre>{:else if variant===2}<div class="b-link-preview">rahunok · #1042 <ArrowUpRight size={18}/></div>{:else}<div class="b-phone-qr" aria-hidden="true"><QrCode size={62}/><div><b>QR / NFC</b><small>{c.shared.chips[1]}</small></div></div>{/if}<div class="b-product-status" class:b-paid={paid}>{#if paid}<Check size={17}/>{:else}<span class="b-pulse"></span>{/if}{paid?c.success:c.pending}</div><p class="b-phone-note">{c.mock}</p><div class="b-home-indicator" aria-hidden="true"></div></div>
</div>