<script lang="ts">
 import { TrendingUp } from '@lucide/svelte';import { compareMonthlyCosts } from '../utils/cost-comparison';import type { BaselineCopy } from './copy';import type { Locale } from '../data/translations';
 let {c,locale}:{c:BaselineCopy;locale:Locale}=$props();
 let turnover=$state<number|undefined>(500000);let rate=$state<number|undefined>(1.5);let terminals=$state<number|undefined>(2);let rent=$state<number|undefined>(400);let fee=$state<number|undefined>(490);let proposed=$state<number|undefined>(0.5);let annual=$state(true);
 const valid=$derived(turnover!==undefined&&turnover<=5000000&&terminals!==undefined&&Number.isInteger(terminals)&&terminals>=0&&terminals<=50&&rent!==undefined&&Number.isFinite(rent)&&rent>=0);
 const costs=$derived(valid?compareMonthlyCosts(turnover,rate,(terminals??0)*(rent??0),fee,proposed):null);
 const factor=$derived(annual?12:1);const max=$derived(Math.max(costs?.current??0,costs?.proposed??0,1));
 const money=(n:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(n);
</script>
<section id="calculator" class="b-section" data-section="8" aria-labelledby="b-roi-heading"><div class="b-wrap"><p class="b-eyebrow">ROI / COST INTELLIGENCE</p><h2 id="b-roi-heading" class="b-heading">{c.roiTitle}</h2><p>{c.roiNote}</p><div class="b-roi b-panel"><div class="b-roi-controls"><div class="b-preset-row">{#each c.product.presets as label,i (label)}<button onclick={()=>{turnover=[150000,500000,2000000][i];terminals=[1,2,8][i];}}>{label}</button>{/each}</div><label class="b-slider-field" for="b-turnover"><span>{c.shared.turnover}<input aria-label={c.shared.turnover} type="number" min="0" max="5000000" step="1000" bind:value={turnover}/></span><input id="b-turnover" type="range" min="0" max="5000000" step="1000" bind:value={turnover}/></label><label class="b-slider-field" for="b-rate"><span>{c.shared.currentRate}<input aria-label={c.shared.currentRate} type="number" min="0" max="100" step="0.1" bind:value={rate}/></span><input id="b-rate" type="range" min="0" max="100" step="0.1" bind:value={rate}/></label><label class="b-slider-field" for="b-terminals"><span>{c.product.terminals}<input aria-label={c.product.terminals} type="number" min="0" max="50" step="1" bind:value={terminals}/></span><input id="b-terminals" type="range" min="0" max="50" step="1" bind:value={terminals}/></label><details class="b-assumptions" open><summary>{c.product.assumptions}</summary><div><label class="b-field">{c.product.rentUnit}<input type="number" min="0" step="1" bind:value={rent}/></label><label class="b-field">{c.shared.fee}<input type="number" min="0" step="1" bind:value={fee}/></label><label class="b-field">{c.shared.rate}<input type="number" min="0" max="100" step="0.1" bind:value={proposed}/></label></div></details><p class="b-note">{c.product.sample}</p></div><div class="b-roi-result"><div class="b-roi-top"><TrendingUp size={22}/><div class="b-segmented"><button aria-pressed={!annual} onclick={()=>annual=false}>{c.product.monthly}</button><button aria-pressed={annual} onclick={()=>annual=true}>{c.product.annual}</button></div></div><div class="b-roi-live" aria-live="polite" aria-atomic="true">{#if costs}<p>{costs.difference<0?c.product.negative:c.shared.difference.split(' / ')[0]}</p><strong class:b-negative={costs.difference<0}>{money(costs.difference*factor)}<small> ₴</small></strong><span>{annual?c.product.annual:c.product.monthly}</span>{:else}<p class="b-error">{c.invalidCost}</p>{/if}</div>{#if costs}<div class="b-cost-bars"><div><p>{c.shared.now}<b>{money(costs.current*factor)} ₴</b></p><i style:width={`${costs.current/max*100}%`}></i></div><div><p>{c.shared.after}<b>{money(costs.proposed*factor)} ₴</b></p><i style:width={`${costs.proposed/max*100}%`}></i></div></div><div class="b-roi-formula">{money(costs.current)} − {money(costs.proposed)} = {money(costs.difference)} ₴</div>{/if}<p class="b-note">{c.shared.calcNote}</p></div></div></div></section>