/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.telegram.jsonc --include-runtime=false --env-interface=TelegramWorkerBindings worker/telegram-bindings.d.ts` (hash: 7ed69c1f75c39af9e01a404aea50f1d8)
interface __BaseEnv_TelegramWorkerBindings {
	TELEGRAM_INVOICE_SELF_TEST_ENABLED: "true";
	TELEGRAM_INVOICE_PUBLIC_ORIGIN: "https://letsrealtalk.com";
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_INVOICE_TEST_USER_ID: string;
	TELEGRAM_INVOICE_TEST_CHAT_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/telegram");
	}
	interface Env extends __BaseEnv_TelegramWorkerBindings {}
}
interface TelegramWorkerBindings extends __BaseEnv_TelegramWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TELEGRAM_INVOICE_SELF_TEST_ENABLED" | "TELEGRAM_INVOICE_PUBLIC_ORIGIN" | "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_INVOICE_TEST_USER_ID" | "TELEGRAM_INVOICE_TEST_CHAT_ID">> {}
}
